@baseUrl = http://localhost:8080
@contentType = application/json
@requestID = "requestid-1"

### Create New Supplier
POST {{baseUrl}}/suppliers
X-Request-ID: {{requestID}}
Content-Type: {{contentType}}

{
  "code": "VEND-001",
  "name": "PT. Elektronik Maju Jaya",
  "email": "sales@maju-jaya.com",
  "address": "Kawasan Industri Jababeka Blok C-12"
}

### Get All Suppliers WO reqeuest-id (Paginated)
GET {{baseUrl}}/suppliers?page=0&size=10
Accept: {{contentType}}

### Get All Suppliers (Paginated)
GET {{baseUrl}}/suppliers?page=0&size=10
X-Request-ID: {{requestID}}
Accept: {{contentType}}

### Get Supplier By ID
# Ganti angka '1' dengan ID yang didapat dari hasil Create/List
GET {{baseUrl}}/suppliers/1
X-Request-ID: {{requestID}}
Accept: {{contentType}}

### Update Supplier
PUT {{baseUrl}}/suppliers/1
X-Request-ID: {{requestID}}
Content-Type: {{contentType}}

{
  "code": "VEND-001",
  "name": "PT. Elektronik Maju Jaya (Updated) 2",
  "email": "support@maju-jaya.co.id",
  "address": "Kawasan Industri Jababeka Blok C-12, Bekasi"
}

### Delete Supplier
DELETE {{baseUrl}}/suppliers/1
X-Request-ID: {{requestID}}

### Validation Test: Create with Invalid Email (Will return 400)
POST {{baseUrl}}/suppliers
X-Request-ID: {{requestID}}
Content-Type: {{contentType}}

{
  "code": "VEND-002",
  "name2": "Supplier Error",
  "email": "email-tidak-valid",
  "address": "Alamat Palsu"
}

### Validation Test: Create with Empty Name (Will return 400)
POST {{baseUrl}}/suppliers
X-Request-ID: {{requestID}}
Content-Type: {{contentType}}

{
  "code": "VEND-003"
}