quarkus.grpc.server.port=9001

quarkus.datasource.db-kind=mysql
quarkus.datasource.username=root
quarkus.datasource.password=rootpassword
quarkus.datasource.jdbc.url=jdbc:mysql://localhost:3306/procurement_db

# Flyway: Jalankan migrasi otomatis saat startup
quarkus.flyway.migrate-at-start=true
quarkus.hibernate-orm.database.generation=none
# Test Profile Configuration
# Kita matikan Flyway saat test karena kita menggunakan Mockito (@InjectMock)
%test.quarkus.flyway.enabled=false
%test.quarkus.hibernate-orm.database.generation=none

# LOG
quarkus.log.level=INFO
quarkus.log.category."io.quarkus".level=WARN
quarkus.log.category."org.hibernate".level=WARN
quarkus.log.category."io.netty".level=WARN

%dev.quarkus.log.console.json=false
%dev.quarkus.hibernate-orm.log.sql=true
%dev.quarkus.hibernate-orm.log.format-sql=true
%dev.quarkus.log.category."com.pconk.procurement".level=DEBUG

# Di Dev Mode (Text), kita harus definisikan formatnya agar memunculkan MDC (request_id)
# %X{request_id} akan mengambil nilai dari MDC yang di-set di HttpLoggingFilter
%dev.quarkus.log.console.format=%d{HH:mm:ss} %-5p [%c] (%t) [%X{request_id}] %s%e%n

%prod.quarkus.log.console.json=true
# Menyertakan MDC (X-Request-ID) ke dalam JSON log secara otomatis
%prod.quarkus.log.console.json.mdc=true 


# Menghapus field yang tidak perlu agar log lebih bersih (seperti di Go)
quarkus.log.console.json.excluded-keys=processName,processId,threadName,hostName,loggerClassName
################### END LOG ######################################################
