name: Procurement Service CI

on:
  push:
    branches: [ "main", "master" ]
  pull_request:
    branches: [ "main", "master" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Set up JDK 25
        uses: actions/setup-java@v4
        with:
          java-version: '25'
          distribution: 'temurin'
          cache: maven

      - name: Grant execute permission for mvnw
        run: chmod +x mvnw

      - name: Build and Test
        run: ./mvnw -B verify
        env:
          QUARKUS_HIBERNATE_ORM_DATABASE_GENERATION: none
          QUARKUS_FLYWAY_ENABLED: false
